# Generated by Django 3.2.9 on 2021-12-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211208_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleModel',
        ),
    ]
