# Generated by Django 3.2.9 on 2021-12-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehiclemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
