# Generated by Django 3.2.9 on 2021-12-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211208_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
